junior_siteinterne:
    resource: "@Junior/SiteinterneBundle/Resources/config/routing.yml"
    prefix:   /platal

junior_site:
    resource: "@Junior/SiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /platal/login
    defaults:  { _controller: JuniorSiteinterneBundle:Security:login }

login_check:
    pattern:   /platal/login_check

logout:
    pattern:   /platal/logout