<?php

namespace Proxies\__CG__\Junior\SiteinterneBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Junior\SiteinterneBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'salt', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'hash', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'numSecu', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'centreSecu', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'ville', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'codeBanque', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'codeGuichet', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'compte', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'cle', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'domiciliation', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'titulaire', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'iban', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'bic', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'nationalite', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'promo', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'inscrit', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'inscritLe');
        }

        return array('__isInitialized__', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'salt', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'hash', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'numSecu', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'centreSecu', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'ville', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'codeBanque', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'codeGuichet', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'compte', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'cle', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'domiciliation', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'titulaire', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'iban', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'bic', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'nationalite', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'promo', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'inscrit', '' . "\0" . 'Junior\\SiteinterneBundle\\Entity\\User' . "\0" . 'inscritLe');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNames($names)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNames', array($names));

        return parent::setNames($names);
    }

    /**
     * {@inheritDoc}
     */
    public function getNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNames', array());

        return parent::getNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromo($promo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromo', array($promo));

        return parent::setPromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromo', array());

        return parent::getPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscrit($inscrit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscrit', array($inscrit));

        return parent::setInscrit($inscrit);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscrit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscrit', array());

        return parent::getInscrit();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscritLe($inscritLe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscritLe', array($inscritLe));

        return parent::setInscritLe($inscritLe);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscritLe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscritLe', array());

        return parent::getInscritLe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHash($hash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHash', array($hash));

        return parent::setHash($hash);
    }

    /**
     * {@inheritDoc}
     */
    public function getHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHash', array());

        return parent::getHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSecu($numSecu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSecu', array($numSecu));

        return parent::setNumSecu($numSecu);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSecu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSecu', array());

        return parent::getNumSecu();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentreSecu($centreSecu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentreSecu', array($centreSecu));

        return parent::setCentreSecu($centreSecu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentreSecu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentreSecu', array());

        return parent::getCentreSecu();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeBanque($codeBanque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeBanque', array($codeBanque));

        return parent::setCodeBanque($codeBanque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeBanque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeBanque', array());

        return parent::getCodeBanque();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeGuichet($codeGuichet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeGuichet', array($codeGuichet));

        return parent::setCodeGuichet($codeGuichet);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeGuichet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeGuichet', array());

        return parent::getCodeGuichet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompte($compte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompte', array($compte));

        return parent::setCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompte', array());

        return parent::getCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCle($cle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCle', array($cle));

        return parent::setCle($cle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCle', array());

        return parent::getCle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomiciliation($domiciliation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomiciliation', array($domiciliation));

        return parent::setDomiciliation($domiciliation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomiciliation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomiciliation', array());

        return parent::getDomiciliation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulaire($titulaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulaire', array($titulaire));

        return parent::setTitulaire($titulaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulaire', array());

        return parent::getTitulaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban($iban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban', array($iban));

        return parent::setIban($iban);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban', array());

        return parent::getIban();
    }

    /**
     * {@inheritDoc}
     */
    public function setBic($bic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBic', array($bic));

        return parent::setBic($bic);
    }

    /**
     * {@inheritDoc}
     */
    public function getBic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBic', array());

        return parent::getBic();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite($nationalite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', array($nationalite));

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', array());

        return parent::getNationalite();
    }

}
