<?php

namespace Junior\SiteinterneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemarquesDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemarquesDocumentRepository extends EntityRepository
{
}
