<?php

namespace Junior\SiteinterneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getProchainReferent(\Junior\SiteinterneBundle\Entity\User $dernierReferent)
	{
		$users=$this
			->createQueryBuilder('a')
			->orderBy('a.id','DESC')
			->getQuery()
			->getResult()
		;

		$polemission = array();
		foreach($users as $u){
			foreach($u->getRoles() as $r){
				if($r == "ROLE_POLEMISSION"){
					$polemission[] = $u; 
				}
			}
		}
		
		if(count($polemission) != 0){
			if(!in_array($dernierReferent, $polemission)){
				return $polemission[0];
			}
				$indiceSuivant = (array_search($dernierReferent, $polemission)+1)%count($polemission);
				$referentSuivant = $polemission[$indiceSuivant];
				return $referentSuivant;

		}
		return null;
	}
}
